GET http://localhost:7777/stations
Accept: application/json

###
GET http://localhost:7777/stations?code=LXHG
Accept: application/json

###
GET http://localhost:7777/stations?name=领秀慧谷
Accept: application/json

###
GET http://localhost:7777/stations?status=NORMAL
Accept: application/json

###
GET http://localhost:7777/stations?description=xxxx
Accept: application/json

