GET http://localhost:7777/addresses
Accept: application/json

###
GET http://localhost:7777/addresses?code=ZXZ
Accept: application/json

###
GET http://localhost:7777/addresses?name=朱
Accept: application/json

###
GET http://localhost:7777/addresses?coordinate=BD09
Accept: application/json

###
GET http://localhost:7777/addresses?latitude=116.311379&longitude=40.102627
Accept: application/json

###
GET http://localhost:7777/addresses?areaCode=110114013004
Accept: application/json

###
GET http://localhost:7777/addresses?description=领秀慧谷
Accept: application/json

