server:
  port: 7777
spring:
  datasource:
    username: ningyu
    password: 123456
    url: jdbc:mysql://localhost:3306/shuttle_locator
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  influx:
    url: http://localhost:8086
    token: SHROsMFwG6iTpz-_WSR3GsHxywZ0oUu68vYaKu1R4v6b4jrgfgKyjs1B0au1L9Ble0hI1RtG6YvAhNfma0RkVw==
    org: tony
    bucket: shuttle_locator
    flushInterval: 1000
    bufferLimit: 10000
    jitterInterval: 1000
    retryInterval: 5000
