server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123@ningyu.me
    url: jdbc:mysql://192.168.5.251:3306/shuttle_nuoche?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#    username: cmp_dev
#    password: T9Q&xkXrCcmemGqZ
#    url: jdbc:mysql://11.11.176.139:3306/cmp_product?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: never
logging:
  file:
    name: shuttle-nuoche.log
  logback:
    rollingpolicy:
      file-name-pattern: shuttle-nuoche-%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      total-size-cap: 10MB
      max-history: 30
      clean-history-on-start: false
